### ISSUE TITLE
[REQUEST]Letter for gear box instead of number ? 

### ISSUE THREAD

**Issue by Vince56190** [agronick/aa-torque#102]
I use AATorque to display the ratio of my gearbox but the gauges do not allow me to display letters like P R and N, is it possible to add that?

**Comment by agronick** [comment]
You need a custom expression under unit conversion. This is the one I use `IF(a == 70, "P", IF(a == 60, "N", a))`. You just chain a bunch of IF else statements together, basically. See the EvalEx documentation for IF.

**Comment by Vince56190** [comment]
the conversion works on the small displays but not on the main gauges, see the photos, they are the same PID with the same conversion.small one indicates P, R and N. The big one  0 ( for P and R) or 5 (for N), I suppose that the main gauges do not accept letters.
![20240106_182256 (1)](https://github.com/agronick/aa-torque/assets/147246549/085d7f3b-754c-4e0e-b74b-6c07b23a09ed)

**Comment by agronick** [comment]
No, they don't.

**Comment by Vince56190** [comment]
Could this be added? this option could make it possible to create visual alerts for example: IF (a > 150, "ALERT", a) (I do not know if this calculation is possible with EvalEx), the gauge would indicate ALERT instead of the probe value.

**Comment by agronick** [comment]
Maybe have a light or illuminate the background or something. I think it would be better to just have ranges. The EvelEx stuff is too complex for some users.

**Comment by Vince56190** [comment]
Alert FAP ( DPF) done !!
![20240113_142424](https://github.com/agronick/aa-torque/assets/147246549/b6fecc1f-5330-4f27-8694-5dcd762598f2)

**Comment by agronick** [comment]
Glad you got everything working
