### ISSUE TITLE
How to Change from km/h to mph?

### ISSUE THREAD

**Issue by Mikeshortnow** [agronick/aa-torque#14]
Hi I'm using the AA torque plugin and it work awesome but I have one minor issue and that is how to change the km/h to mph there seems to be no setting or formula conversation.i know this app is still in work progress so can you guys work on that also

**Comment by MarMed** [comment]
You can enter the formula
a * 0.621371

**Comment by agronick** [comment]
Will be in the next release

**Comment by Mikeshortnow** [comment]
Thanks looking forward to it
