### ISSUE TITLE
[REQUEST] AA Torque name also in Android launcher

### ISSUE THREAD

**Issue by cioce78** [agronick/aa-torque#18]
Hi, please rename the APP as "AA Torque" also in standard Android launcher for all languages, now is using old name "Setting Performance Monitor".

**Comment by agronick** [comment]
You can help translate here: https://poeditor.com/projects/view?id=653187

**Comment by Airislv24** [comment]
by this link https://poeditor.com/projects/view?id=653187
![image](https://github.com/agronick/aa-torque/assets/147970540/c8449ad5-638b-442a-a3ce-0e22dee21e8d)

**Comment by agronick** [comment]
Sorry this link https://poeditor.com/join/project/yttme0y1VZ

**Comment by emiliodeme** [comment]
Can't help on translation as it returns project can't accept more contributors. Would like to help on a Portuguese (BR) translation.

**Comment by agronick** [comment]
I contacted the people at the translation service. It should be fixed now. They re-enabled the features that were missing.
