### ISSUE TITLE
[BUG] Connection to ECU

### ISSUE THREAD

**Issue by EgeK2** [agronick/aa-torque#19]
Hey! I have this problem with my Mazda 2 2016. First i open Torque Pro app and connect to the OBD2 then im connection my phone to Android Auto but when i choose the app on the screen it says Connection to Ecu but never connects. At the sametime Torque Pro works well in the background also. ( i user kinginstaller)

**Comment by VenomCodeDev** [comment]
Same issue. Samsung Fold 3 with some generic aftermarket AA head unit via wireless connection. Stays at "Connecting to ECU..." even though on the phone i can use torque no problem.

**Comment by EgeK2** [comment]
I fixed it. Forgot to edit element settings. Just sepect element settings and edit all

**Comment by agronick** [comment]
Yeah, that is a bit of a usability issue. It just says that until it gets a non-zero value. It used to actually check the ECU but it was faster to just wait for the first non-zero value.

**Comment by agronick** [comment]
If anyone wants to try making the work better you can start looking here https://github.com/agronick/aa-torque/blob/30e152b0f5ede0daab4551f0dfe711c5ad57b940/app/src/main/java/com/aatorque/stats/TorqueRefresher.kt#L56
