### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SalvatoreNoschese** [agronick/aa-torque#20]
Tried to install as described, but still result installed from king installer (not PlayStore) then  cannot found in AA.
P7P with A14 stable.

![Screenshot_20231005-185308](https://github.com/agronick/aa-torque/assets/16841896/32d23ab7-7253-450a-ba03-28675578eb54)

**Comment by agronick** [comment]
I can't help with issues that involve getting it working on your specific phone. Read the Kingstaller wiki or open an issue with Kingstaller. This isn't a problem with the code of the app.
