### ISSUE TITLE
Temperatures not reporting correctly

### ISSUE THREAD

**Issue by sinistriel** [agronick/aa-torque#21]
When you select "whole numbers" it rounds the temperatures up by 20 plus degrees in the new releases, earlier releases did not have this issue. 

![20231004_194832](https://github.com/agronick/aa-torque/assets/147092298/3b24746a-8820-4fac-95af-624aa1696b11)
![Screenshot_20231004_194848_Torque](https://github.com/agronick/aa-torque/assets/147092298/2241ca57-dc4c-4193-9305-62c172c9766f)

**Comment by agronick** [comment]
What equation are you using for the conversion? Can you see it moving 20 degrees just by checking and unchecking the box?

**Comment by sinistriel** [comment]
Yeah if I check or uncheck the box it will move 20~ degrees. Unchecked it
matches the display on Torque exactly then bumps up by 20~ when checked.

**Comment by sinistriel** [comment]
I'm using the unit conversion, and this behavior started after the last few
updates, none of the betas had this issue.

**Comment by agronick** [comment]
There was a bug, will be fixed in the next release
