### ISSUE TITLE
ODBC adapter 

### ISSUE THREAD

**Issue by DokVWTSi** [agronick/aa-torque#33]
My ODBC adapter is Wi-Fi. Will it work or does the adapter need to be Bluetooth? I have the program opening but tells me "connecting to device.." going into Torque Pro the device works perfectly as soon as I have connected to the ELM Wi-Fi network. Love the interface and would really like to get it working. Thank you and well done with the dev. It's awesome

**Comment by agronick** [comment]
It should work fine. Make sure your Torque is updated and you have configured your gauges.

**Comment by Fabio1968** [comment]
If I understand correctly, can the OBD be connected via wifi without using the USB cable from the phone to the car?
thanks for your reply

**Comment by agronick** [comment]
Yes, it is just asking Torque for data. If it works with Torque it should work here.

**Comment by Fabio1968** [comment]
Thank you for your answer. Can you recommend a wifi OBD model? There are several models and I don't know exactly what features it should have. Thank you

**Comment by agronick** [comment]
I use Bluetooth. I use the wifi for wireless android auto.
