### ISSUE TITLE
[BUG] Custom PIDs are wrongly displayed in the AA-Torque

### ISSUE THREAD

**Issue by aivus** [agronick/aa-torque#40]
**Describe the bug**

I've created 3 custom PIDs in Torque app, but AA-Torque showed only one of them duplicated 3 times.

**To Reproduce**
1. Create several custom PIDs in Torque app
2. In AA-Torque try to use them

**Expected behavior**
All custom PIDs are displayed in AA-Torque

**App version:** 10.0.40

**Screenshots**
![Screenshot_20231012-162600_AA Torque](https://github.com/agronick/aa-torque/assets/1021703/232f1983-bd25-4c14-b578-e2ead9983fbd)
![Screenshot_20231012-162621_Torque](https://github.com/agronick/aa-torque/assets/1021703/8ae78724-a5af-450f-959d-53e70ea68d5b)

**Comment by agronick** [comment]
Can you make a screen recording? Is your Torque updated?

**Comment by that1cardude** [comment]
I also have a few custom PIDS in Torque Pro but when I choose them in AA Torque it does not show the values. But the actual torque pro app does.

**Comment by aivus** [comment]
@agronick 

> Is your Torque updated?

Latest version of Torque app.

Screen recording: https://youtube.com/shorts/5dl7g6SA_zc

**Comment by aivus** [comment]
@that1cardude please create separate issue

**Comment by agronick** [comment]
Can you export your pids from torque to a CSV and attach them? I think Torque is probably giving bad data. I have seen other bugs on that page in Torque.

**Comment by DanSilva926** [comment]
I have a custom PID and they are working correctly, check the values ​​in the Torque app if they are correct?

**Comment by aivus** [comment]
@DanSilva926 It's more about PIDs, not the data received from car.
As you can see from the screenshots and video above Torque App shows PIDs correctly in the list.

@agronick I did export from Torque, removed all custom PIDs, cleared all data of AA Torque app, imported custom PIDs to Torque. And still having this.

Attaching the exported PIDs from Torque app: [exportedPIDs.csv](https://github.com/agronick/aa-torque/files/13294205/exportedPIDs.csv)

**Comment by MasterPIC** [comment]
I'm thinking about a bug related to common "Battery" string followed by space character. If this is the case then You can try to set something like Battery_xxx, Battery_yyy as PID name...

**Comment by aivus** [comment]
@agronick if it's (☝️ ) a case and no issues on AA-Torque side - feel free to close the issue

**Comment by agronick** [comment]
Sorry for the delay with this. I finally got a chance to look at it. The problem is that your PIDs are not in hexidecimal format. They are in decimal. The torque app might have some code to do the conversion but it is coming back through the service as 3 pids named `7ffffffe,65`. All the `f` characters look like it is encountering some kind of overflow since that is the biggest digit in hex. Convert your pid to hex and it will probably work.
