### ISSUE TITLE
[BUG]Screen preview= App crashed

### ISSUE THREAD

**Issue by Vince56190** [agronick/aa-torque#42]
When I select the preview of my configuration, the application crashes. Do you want the crash report?
Android 13 , Pixel 6a.

**To Reproduce**
Including a logcat or Debug log is very helpful. Use Google to find out how to get those on your specific phone/Android version.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by agronick** [comment]
See if this is happening on the latest version

**Comment by Vince56190** [comment]
it's ok on the last version , no crash anymore.
