### ISSUE TITLE
[BUG] Artifacts on the screen on version RC9.1

### ISSUE THREAD

**Issue by Airislv24** [agronick/aa-torque#43]
My car Renault Captur, headunit 7 inch.
After update version from RC8.4 to RC9.1, I see artifacts on screen. Artifacts on the right side of the screen.
Change background doesn't help.
![image](https://github.com/agronick/aa-torque/assets/147970540/c9e114e3-219d-430a-b591-511caf87832f)

**Comment by agronick** [comment]
I can't reproduce it but I have a rough idea what is causing it. When version 10 is released let me know if it is fixed.

**Comment by Airislv24** [comment]
ok, thank You!
