### ISSUE TITLE
[BUG] Crash at Startup

### ISSUE THREAD

**Issue by aross6** [agronick/aa-torque#48]
Crash at Startup when launching app in AA. Crash Report submitted via email.

**Comment by agronick** [comment]
I don't see it. Are you using the newest version?

**Comment by aross6** [comment]
> I don't see it. Are you using the newest version?

Yes, was using 10.0.57 RC10. Do you need me to resend the Crash Report to you gmail?

**Comment by Vince56190** [comment]
on the last version install with kinginstaller  , no crash anymore ( android 13 , Pixel 6a)
