### ISSUE TITLE
[BUG] Engine Oil temperature not work

### ISSUE THREAD

**Issue by elnidalarguia** [agronick/aa-torque#50]
The engine oil temperature is not displayed, always marks the minimum temperature that you mark in the app to be displayed, I tried putting without decimals and it does not work either.

**Comment by elnidalarguia** [comment]
![Screenshot_2023-10-18-09-16-30-78_9e5b76f079b560618247a9ff49c28e85](https://github.com/agronick/aa-torque/assets/148241622/d35eae1f-4803-46bd-94ed-df4578ca7f8e)

**Comment by DanSilva926** [comment]
![IMG20231020194624](https://github.com/agronick/aa-torque/assets/92631888/cfcd5c3d-1554-461d-bf59-ba25c1ab42d0)
 Oil work temp

**Comment by elnidalarguia** [comment]
Ok it's Torque's fault that it doesn't show me the temperature. How can I create a custom pid.

**Comment by DanSilva926** [comment]
In the torque settings there are extra pid options, you can add several brands
