### ISSUE TITLE
[BUG] dont have options for remove background 

### ISSUE THREAD

**Issue by DanSilva926** [agronick/aa-torque#51]
![Screenshot_2023-10-20-20-14-48-89_9e5b76f079b560618247a9ff49c28e85](https://github.com/agronick/aa-torque/assets/92631888/506f4f01-ac64-4020-b8c9-899a07276cce)

I selected a background to see if I liked one but now I can't remove it and I'm left with no background.

**Comment by agronick** [comment]
Black is remove background

**Comment by DanSilva926** [comment]
> Preto é remover fundo

No ,is diferent .
the black one has a line on top of the pressure gauges, I'll leave a photo later

![IMG20231020194624](https://github.com/agronick/aa-torque/assets/92631888/cd059918-cf7b-4cd8-9f9a-c162df4d5df4)

**Comment by DanSilva926** [comment]
![Imagem WhatsApp 2023-10-23 às 10 19 28_dc56bcfe](https://github.com/agronick/aa-torque/assets/92631888/b7f620d6-cef4-4bc2-ac61-5bdd83468906)

if you choose black, that line appears at the top
