### ISSUE TITLE
[BUG]oil temperature

### ISSUE THREAD

**Issue by Fabio1968** [agronick/aa-torque#56]
Hi, congratulations on the app, it's very well done.  My oil temperature gauge doesn't work.  does this happen to you too?  

> thank you for your response

 :exclamation:  Issues that aren't in English will  be closed and igored.  |
|-----------------------------------------|

**Describe the bug**
Be as descriptive as possible, and write in English.
Make sure you've read the Readme and searched for similar issues before asking a question.
Issues not in English or without any detail will not be closed and ignored. 
Be kind and respectful and maybe most importantly: Don't be lazy (just posting a duplicate error like "it's crashing" or "it doesn't get data") while you're expecting me to do all the work for free 😄

**To Reproduce**
Including a logcat or Debug log is very helpful. Use Google to find out how to get those on your specific phone/Android version.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by agronick** [comment]
Is oil temperature reported in torque?

**Comment by Fabio1968** [comment]
Thanks for the reply.  I had assumed that the sensor was detected by torque and consequently by aa-torque and instead it doesn't work

**Comment by agronick** [comment]
Yeah, its just asking torque for a list of PIDs. It isn't checking that they all work, that would take too long. Maybe eventually I'll have it report live data in the list like Torque does.
