### ISSUE TITLE
[REQUEST]Turbo pressure

### ISSUE THREAD

**Issue by Mika91100** [agronick/aa-torque#77]
Hello first of all thank you for this magnificent application I wanted to report a small problem that I am encountering with the turbo pressure.  I have a turbo that takes a little more than 3 bar and when I set 3.5 bar in the application once on the road it never exceeds 1.6 bar.  Can you please make something that has greater reading value.  Thanks in advance .

**Comment by agronick** [comment]
Change the max value. The app doesn't know it is displaying turbo pressure. It just takes numbers from torque and puts them on the screen.

**Comment by Mika91100** [comment]
Hello thank you for your response in fact I have already modified the value to 4 bar but the reading is up to 1.5 1.6.

**Comment by agronick** [comment]
Do you see the values reported correctly in Torque? The app doesn't know what value is what. It is just asking Torque for data.
