### ISSUE TITLE
[BUG] Misplaced graduations on 16.5 

### ISSUE THREAD

**Issue by Vince56190** [agronick/aa-torque#82]
With the new version, the gauge values are too close to the cente
![Screenshot_20231125_214545_AA Torque](https://github.com/agronick/aa-torque/assets/147246549/6207e6f2-a521-4bac-bf27-1756ce6a5106)

**Comment by agronick** [comment]
I think the biggest issue is just that font tends to be larger than the other fonts. I can try to shrink it.

**Comment by Vince56190** [comment]
the problem is always present, whatever the font
![20231206_131617](https://github.com/agronick/aa-torque/assets/147246549/29008450-f279-4492-b396-6e16794e041d)

**Comment by Vince56190** [comment]
before it was like that : 
![20231111_154354](https://github.com/agronick/aa-torque/assets/147246549/17b05121-0e68-484a-a888-7adaa8e8b250)

**Comment by agronick** [comment]
Setting will be added in the next version which will be released in a few minutes
