### ISSUE TITLE
[BUG] [REQUEST?] Small Screen Layout Fix of 10.0.94 Scales Improperly (broke midsize screen layout)

### ISSUE THREAD

**Issue by Mtn-Mike** [agronick/aa-torque#88]
**Describe the bug**
Version 10.0.94, "fix layout on smaller screens", doesn't scale properly.  See image.
![12-13-2023 10-09-56 PM](https://github.com/agronick/aa-torque/assets/147363195/bbc8cea7-c11d-4fc2-8218-a96b9a551ae5)

I think the display from v10.0.93 is near perfect.  Maybe provide an option in the app for small, medium, and large displays that all scale a little differently, and let the user choose which fits best.

**Comment by Mtn-Mike** [comment]
Hey, it's back (v10.0.103)!  Nice work, thanks!

Although I just found out my S21 will be force-updated to Android 14 soon, which seems to be a death sentence for AA-Torque.  :(

**Comment by anderml1955** [comment]
S21 Ultra Pro, Android 14 fully updated, latest AA & Torque. Working perfectly. Great work.
