### ISSUE TITLE
[BUG] preview mode doesn't show guages

### ISSUE THREAD

**Issue by Taza13** [agronick/aa-torque#97]
With 2.0.8 when I preview my guages in the app no guages show or any info
This is on Samsung S23 Ultra Android 14 

Here are a few screenshots as images
![Screenshot_20231228_225901_AA Torque](https://github.com/agronick/aa-torque/assets/56674733/c31dcd25-9753-4295-bc18-a2eb38a6ed76)
![Screenshot_20231228_225912_AA Torque](https://github.com/agronick/aa-torque/assets/56674733/7173cf1b-606f-4e38-b611-74824f954ca9)
![Screenshot_20231228_225917_AA Torque](https://github.com/agronick/aa-torque/assets/56674733/1fd0e81a-d7f8-4380-af23-85f776c1c27c)

**Comment by agronick** [comment]
Turn the opacity up. It will be fixed in the next version.

**Comment by Taza13** [comment]
Legend thanks heaps
