### ISSUE TITLE
[BUG] guage opaqueness min is 50 

### ISSUE THREAD

**Issue by Taza13** [agronick/aa-torque#99]
The opacity minimum is 50 not 0
![Screenshot_20231229_112457_AA Torque](https://github.com/agronick/aa-torque/assets/56674733/ef13f8ba-21bd-4f06-bf94-6294015f9a93)
![Screenshot_20231229_112715_AA Torque](https://github.com/agronick/aa-torque/assets/56674733/111c2b35-2ab2-4d9e-bf3a-6de0f055a899)

**Comment by agronick** [comment]
It's supposed to be 50. It was reading as 0 if it was never changed.

**Comment by Taza13** [comment]
But I would like to make it 0 opaque so its clearer as my head unit cops a lot of sunlight

**Comment by agronick** [comment]
0 means it isn't visible at all
